name: shop1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.5.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_riverpod: ^2.6.1
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.0
  build_runner: ^2.5.4
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.0
  drift_dev: ^2.26.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf